/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIndexRouteImport } from './routes/transfers.index'
import { Route as TacticsIndexRouteImport } from './routes/tactics.index'
import { Route as SquadIndexRouteImport } from './routes/squad.index'
import { Route as SeasonsIndexRouteImport } from './routes/seasons.index'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as SavesIndexRouteImport } from './routes/saves.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as LeagueIndexRouteImport } from './routes/league.index'
import { Route as ClubIndexRouteImport } from './routes/club.index'
import { Route as TransfersPlayerIdRouteImport } from './routes/transfers.$playerId'
import { Route as SeasonsSeasonRouteImport } from './routes/seasons.$season'
import { Route as SeasonSummaryRouteImport } from './routes/season.summary'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as LeagueClubsClubIdRouteImport } from './routes/league.clubs.$clubId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIndexRoute = TransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsIndexRoute = TacticsIndexRouteImport.update({
  id: '/tactics/',
  path: '/tactics/',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadIndexRoute = SquadIndexRouteImport.update({
  id: '/squad/',
  path: '/squad/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsIndexRoute = SeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/scouts/',
  path: '/scouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesIndexRoute = SavesIndexRouteImport.update({
  id: '/saves/',
  path: '/saves/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueIndexRoute = LeagueIndexRouteImport.update({
  id: '/league/',
  path: '/league/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIndexRoute = ClubIndexRouteImport.update({
  id: '/club/',
  path: '/club/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersPlayerIdRoute = TransfersPlayerIdRouteImport.update({
  id: '/transfers/$playerId',
  path: '/transfers/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsSeasonRoute = SeasonsSeasonRouteImport.update({
  id: '/seasons/$season',
  path: '/seasons/$season',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonSummaryRoute = SeasonSummaryRouteImport.update({
  id: '/season/summary',
  path: '/season/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueClubsClubIdRoute = LeagueClubsClubIdRouteImport.update({
  id: '/league/clubs/$clubId',
  path: '/league/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches/$id': typeof MatchesIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/season/summary': typeof SeasonSummaryRoute
  '/seasons/$season': typeof SeasonsSeasonRoute
  '/transfers/$playerId': typeof TransfersPlayerIdRoute
  '/club/': typeof ClubIndexRoute
  '/league/': typeof LeagueIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/saves/': typeof SavesIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/league/clubs/$clubId': typeof LeagueClubsClubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches/$id': typeof MatchesIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/season/summary': typeof SeasonSummaryRoute
  '/seasons/$season': typeof SeasonsSeasonRoute
  '/transfers/$playerId': typeof TransfersPlayerIdRoute
  '/club': typeof ClubIndexRoute
  '/league': typeof LeagueIndexRoute
  '/players': typeof PlayersIndexRoute
  '/saves': typeof SavesIndexRoute
  '/scouts': typeof ScoutsIndexRoute
  '/seasons': typeof SeasonsIndexRoute
  '/squad': typeof SquadIndexRoute
  '/tactics': typeof TacticsIndexRoute
  '/transfers': typeof TransfersIndexRoute
  '/league/clubs/$clubId': typeof LeagueClubsClubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches/$id': typeof MatchesIdRoute
  '/players/$id': typeof PlayersIdRoute
  '/season/summary': typeof SeasonSummaryRoute
  '/seasons/$season': typeof SeasonsSeasonRoute
  '/transfers/$playerId': typeof TransfersPlayerIdRoute
  '/club/': typeof ClubIndexRoute
  '/league/': typeof LeagueIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/saves/': typeof SavesIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
  '/seasons/': typeof SeasonsIndexRoute
  '/squad/': typeof SquadIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/transfers/': typeof TransfersIndexRoute
  '/league/clubs/$clubId': typeof LeagueClubsClubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches/$id'
    | '/players/$id'
    | '/season/summary'
    | '/seasons/$season'
    | '/transfers/$playerId'
    | '/club/'
    | '/league/'
    | '/players/'
    | '/saves/'
    | '/scouts/'
    | '/seasons/'
    | '/squad/'
    | '/tactics/'
    | '/transfers/'
    | '/league/clubs/$clubId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches/$id'
    | '/players/$id'
    | '/season/summary'
    | '/seasons/$season'
    | '/transfers/$playerId'
    | '/club'
    | '/league'
    | '/players'
    | '/saves'
    | '/scouts'
    | '/seasons'
    | '/squad'
    | '/tactics'
    | '/transfers'
    | '/league/clubs/$clubId'
  id:
    | '__root__'
    | '/'
    | '/matches/$id'
    | '/players/$id'
    | '/season/summary'
    | '/seasons/$season'
    | '/transfers/$playerId'
    | '/club/'
    | '/league/'
    | '/players/'
    | '/saves/'
    | '/scouts/'
    | '/seasons/'
    | '/squad/'
    | '/tactics/'
    | '/transfers/'
    | '/league/clubs/$clubId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesIdRoute: typeof MatchesIdRoute
  PlayersIdRoute: typeof PlayersIdRoute
  SeasonSummaryRoute: typeof SeasonSummaryRoute
  SeasonsSeasonRoute: typeof SeasonsSeasonRoute
  TransfersPlayerIdRoute: typeof TransfersPlayerIdRoute
  ClubIndexRoute: typeof ClubIndexRoute
  LeagueIndexRoute: typeof LeagueIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  SavesIndexRoute: typeof SavesIndexRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
  SeasonsIndexRoute: typeof SeasonsIndexRoute
  SquadIndexRoute: typeof SquadIndexRoute
  TacticsIndexRoute: typeof TacticsIndexRoute
  TransfersIndexRoute: typeof TransfersIndexRoute
  LeagueClubsClubIdRoute: typeof LeagueClubsClubIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/': {
      id: '/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof TransfersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/': {
      id: '/tactics/'
      path: '/tactics'
      fullPath: '/tactics/'
      preLoaderRoute: typeof TacticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad/': {
      id: '/squad/'
      path: '/squad'
      fullPath: '/squad/'
      preLoaderRoute: typeof SquadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/': {
      id: '/seasons/'
      path: '/seasons'
      fullPath: '/seasons/'
      preLoaderRoute: typeof SeasonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/scouts'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/': {
      id: '/saves/'
      path: '/saves'
      fullPath: '/saves/'
      preLoaderRoute: typeof SavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/': {
      id: '/league/'
      path: '/league'
      fullPath: '/league/'
      preLoaderRoute: typeof LeagueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/': {
      id: '/club/'
      path: '/club'
      fullPath: '/club/'
      preLoaderRoute: typeof ClubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$playerId': {
      id: '/transfers/$playerId'
      path: '/transfers/$playerId'
      fullPath: '/transfers/$playerId'
      preLoaderRoute: typeof TransfersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$season': {
      id: '/seasons/$season'
      path: '/seasons/$season'
      fullPath: '/seasons/$season'
      preLoaderRoute: typeof SeasonsSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season/summary': {
      id: '/season/summary'
      path: '/season/summary'
      fullPath: '/season/summary'
      preLoaderRoute: typeof SeasonSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/clubs/$clubId': {
      id: '/league/clubs/$clubId'
      path: '/league/clubs/$clubId'
      fullPath: '/league/clubs/$clubId'
      preLoaderRoute: typeof LeagueClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesIdRoute: MatchesIdRoute,
  PlayersIdRoute: PlayersIdRoute,
  SeasonSummaryRoute: SeasonSummaryRoute,
  SeasonsSeasonRoute: SeasonsSeasonRoute,
  TransfersPlayerIdRoute: TransfersPlayerIdRoute,
  ClubIndexRoute: ClubIndexRoute,
  LeagueIndexRoute: LeagueIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  SavesIndexRoute: SavesIndexRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
  SeasonsIndexRoute: SeasonsIndexRoute,
  SquadIndexRoute: SquadIndexRoute,
  TacticsIndexRoute: TacticsIndexRoute,
  TransfersIndexRoute: TransfersIndexRoute,
  LeagueClubsClubIdRoute: LeagueClubsClubIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
