/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoutsIndexRouteImport } from './routes/scouts.index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as ScoutsIdRouteImport } from './routes/scouts.$id'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIndexRoute = ScoutsIndexRouteImport.update({
  id: '/scouts/',
  path: '/scouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsIdRoute = ScoutsIdRouteImport.update({
  id: '/scouts/$id',
  path: '/scouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players/$id': typeof PlayersIdRoute
  '/scouts/$id': typeof ScoutsIdRoute
  '/players/': typeof PlayersIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players/$id': typeof PlayersIdRoute
  '/scouts/$id': typeof ScoutsIdRoute
  '/players': typeof PlayersIndexRoute
  '/scouts': typeof ScoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/players/$id': typeof PlayersIdRoute
  '/scouts/$id': typeof ScoutsIdRoute
  '/players/': typeof PlayersIndexRoute
  '/scouts/': typeof ScoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/players/$id' | '/scouts/$id' | '/players/' | '/scouts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/players/$id' | '/scouts/$id' | '/players' | '/scouts'
  id:
    | '__root__'
    | '/'
    | '/players/$id'
    | '/scouts/$id'
    | '/players/'
    | '/scouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersIdRoute: typeof PlayersIdRoute
  ScoutsIdRoute: typeof ScoutsIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScoutsIndexRoute: typeof ScoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/': {
      id: '/scouts/'
      path: '/scouts'
      fullPath: '/scouts/'
      preLoaderRoute: typeof ScoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts/$id': {
      id: '/scouts/$id'
      path: '/scouts/$id'
      fullPath: '/scouts/$id'
      preLoaderRoute: typeof ScoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersIdRoute: PlayersIdRoute,
  ScoutsIdRoute: ScoutsIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScoutsIndexRoute: ScoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
